# ---------------------------
# 🧱 docker-compose.yml (racine)
# ---------------------------
version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geo-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_URI_TPL
      - MONGODB_DB
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: geo-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

