# ---------------------------
# 🧱 docker-compose.yml (racine)
# ---------------------------
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geo-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_URI_TPL=${MONGODB_URI_TPL}
      - MONGODB_DB=${MONGODB_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
    depends_on:
      - maildev
    volumes:
      - ./backend:/app
      - ./backend/generate_secret.py:/app/generate_secret.py
      - ./backend/uploads:/app/uploads         # pour fichiers utilisateur
      - ./backend/data/samples:/app/data/samples  # pour tests de dev
      - ./.env:/app/.env

  maildev:
    container_name: geo-maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: geo-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules  # évite d’écraser node_modules du conteneur
