services:
  backend:
    image: ${IMAGE_BACKEND}
    container_name: geo-backend
    restart: unless-stopped
    env_file:
      - ../shared/env/app.env
      - ../shared/env/secrets.env
    depends_on:
      - mailhog
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      # Persistance des uploads côté hôte
      - ../shared/uploads:/app/uploads
      # (optionnel) logs/app si tu veux des fichiers log persistants
      # - ../shared/logs/backend:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: ${IMAGE_FRONTEND}
    container_name: geo-frontend
    restart: unless-stopped
    env_file:
      - ../shared/env/app.env
    depends_on:
      - backend
      - tiles
    ports:
      - "${FRONTEND_PORT:-80}:80"

  tiles:
    image: nginx:1.25-alpine
    container_name: geo-tiles
    restart: unless-stopped
    command: |
      sh -c "
      rm -f /etc/nginx/conf.d/default.conf &&
      mkdir -p /var/log/nginx /var/cache/nginx/tiles_cache &&
      nginx -g 'daemon off;'
      "
    volumes:
      - ../shared/ops/nginx/tiles.conf:/etc/nginx/conf.d/tiles.conf:ro
      - ../shared/ops/nginx/www:/var/www:ro
      - tiles_cache:/var/cache/nginx/tiles_cache
      - tiles_logs:/var/log/nginx
    ports:
      - "8080:80"  # ou 127.0.0.1:8080:80 si vous voulez le cacher
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1/tiles/_health.png || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: geo-mailhog
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025"  # SMTP, accessible seulement depuis le serveur
      - "127.0.0.1:8025:8025"  # UI Web, accessible via tunnel SSH

volumes:
  tiles_cache:
    driver: local
  tiles_logs:
    driver: local